CREATE TABLE genre (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name varchar(128) UNIQUE  NOT NULL,
	description TEXT NOT NULL,
	INDEX(name)
	);

INSERT INTO `genre` (`id`, `name`, `description`) VALUES
(1, 'Rock', 'Rock music or rock and roll in full name is a genre of popular music that originated as \"rock and roll\" in the United States in the early 1950s, and developed into a range of different styles in the late 1950s, 1960s and later, particularly in the United Kingdom and the United States. Its roots are in 1950s\'American rock and roll when and where it first started, itself heavily influenced by rhythm and blues and country music. Rock music also drew strongly on a number of other genres such as blues and folk, and incorporated influences from jazz, classical and other musical sources.'),
(2, 'Electronic', 'Electronic music is music that employs electronic musical instruments and electronic music technology in its production, an electronic musician being a musician who composes and/or performs such music. In general a distinction can be made between sound produced using electromechanical means and that produced using electronic technology. Examples of electromechanical sound producing devices include the telharmonium, Hammond organ, and the electric guitar. Purely electronic sound production can be achieved using devices such as the theremin, sound synthesizer, and computer.'),
(3, 'Pop', 'Pop music is a genre of popular music that originated in its modern form during the mid-1950s in the United States and the United Kingdom. The terms popular music and pop music are often used interchangeably, although the former describes all music that is popular and includes many disparate styles.'),
(4, 'Jazz', 'Jazz is a genre of music that originated in African-American communities during the late 19th and early 20th century. Jazz emerged in many parts of the United States of independent popular musical styles; linked by the common bonds of European American and African-American musical parentage with a performance orientation. Jazz spans a range of music from ragtime to the present day—a period of over 100 years—and has proved to be very difficult to define. Jazz makes heavy use of improvisation, polyrhythms, syncopation, and the swung note, as well as aspects of European harmony, American popular music, the brass band tradition, and African musical elements such as blue notes and ragtime. A musical group that plays jazz is called a jazz band.'),
(5, 'Hip Hop', 'Hip hop music, also called hip-hop, rap music, or hip-hop music, is a music genre consisting of a stylized rhythmic music that commonly accompanies rapping, a rhythmic and rhyming speech that is chanted. It developed as part of hip hop culture, a subculture defined by four key stylistic elements: MCing/rapping, DJing/scratching, break dancing, and graffiti writing. Other elements include sampling (or synthesis), and beatboxing. While often used to refer to rapping, \"hip hop\" more properly denotes the practice of the entire subculture. The term hip hop music is sometimes used synonymously with the term rap music, though rapping is not a required component of hip hop music; the genre may also incorporate other elements of hip hop culture, including DJing and scratching, beatboxing, and instrumental tracks.'),
(6, 'Disco', 'Disco is a style of music that was most popular from the mid-1970s to the early 1980s, featuring African-American and Latino musicians and audiences, and in private dance parties thrown in the underground gay community of New York. People usually dance to disco music at bars called disco clubs. The word \"disco\" is also used to refer to the style of dancing that people do to disco music, or to the style of clothes that people wear to go disco dancing. Disco music was an up-tempo form of music which included elements of soul, funk and Latin music. It had a strong beat meant for dancing, a steady four-on-the-floor rhythm, and a big bass line, and orchestral instrumentation often included string sections. Disco is dance music too.'),
(7, 'Classical', 'Classical music generally refers to the art music of the Western world, considered to be distinct from Western folk music or popular music traditions. It is sometimes distinguished as Western classical music, as the term classical music also applies to non-Western art music.'),
(8, 'Explore All', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.');
